message

diff --git a/.scripts/pre-commit b/.scripts/pre-commit
--- a/.scripts/pre-commit
+++ b/.scripts/pre-commit
@@ -1,49 +1,78 @@
-#----------------------------------------------------------------
-# PREVENT YOUR CODEBASE GETTING SPOILED BY DEVELOPERS
-# - YOU NEED TO THIS pre-commit file (without any extension) 
-#   at ".git/hooks/" folder.
-# - THEN TRY TO PUT WRONG STYLED/LINT CODE
-#----------------------------------------------------------------
+#!/bin/bash
+
+
+
+echo "*********************************************************"
+echo "Running git pre-commit hook. Making sure that its a valid branch..." 
+echo "*********************************************************"
+
+
+# Branch
 
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
-#----------------------------------------------------------------
-# RESTRICT BRANCHES FROM DIRECT PUSH
-#----------------------------------------------------------------
-if [ "$branch" = "master" ] || [ "$branch" = "Development" ]; then
-  echo "You can't commit directly to $branch"
+echo ""
+echo "Current Branch: $branch"
+echo ""
+
+if [ "$branch" = "dev" ]; then
+  echo "You can't commit directly to dev branch"
   exit 1
 fi
 
-#----------------------------------------------------------------
-# RUN SWIFTLINT  
-#----------------------------------------------------------------
-
-# Run SwiftLint
-START_DATE=$(date +"%s")
-
-SWIFT_LINT=/usr/local/bin/swiftlint
-
-# Run SwiftLint for given filename
-run_swiftlint() {
-local filename="${1}"
-if [[ "${filename##*.}" == "swift" ]]; then
-${SWIFT_LINT} autocorrect --path "${filename}"
-${SWIFT_LINT} lint --path "${filename}"
+if [ "$branch" = "uat" ]; then
+  echo "You can't commit directly to uat branch"
+  exit 1
 fi
-}
 
-if [[ -e "${SWIFT_LINT}" ]]; then
-echo "SwiftLint version: $(${SWIFT_LINT} version)"
-# Run for both staged and unstaged files
-git diff --name-only | while read filename; do run_swiftlint "${filename}"; done
-git diff --cached --name-only | while read filename; do run_swiftlint "${filename}"; done
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
+
+echo ""
+echo "The branch is valid, moving onto next step..."
+echo ""
+
+
+echo "*********************************************************"
+echo "Running git pre-commit hook. Running Swift Lint... "
+echo "*********************************************************"
+
+# Gather the staged files - to make sure changes are saved only for these files.
+stagedFiles=$(git diff --staged --name-only)
+
+# This line is required to make sure it works on Apple Silicon.
+if [[ "$(uname -m)" == arm64 ]]; then
+    export PATH="/opt/homebrew/bin:$PATH"
+fi
+
+# Type a script or drag a script file from your workspace to insert its path.
+if which swiftlint >/dev/null; then
+  swiftlint --fix
 else
-echo "${SWIFT_LINT} is not installed. Please install it first from https://www.github.com/realm/SwiftLint"
-exit 0
+  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
 fi
 
-END_DATE=$(date +"%s")
+status=$?
 
-DIFF=$(($END_DATE - $START_DATE))
-echo "SwiftLint took $(($DIFF / 60)) minutes and $(($DIFF % 60)) seconds to complete."
+if [ "$status" = 0 ] ; then
+    echo "Static analysis found no problems."
+    # Add staged file changes to git
+    for file in $stagedFiles; do
+      if test -f "$file"; then
+        git add $file
+      fi
+    done
+    #Exit
+    exit 0
+else
+    echo "*********************************************************"
+    echo "       ********************************************      "
+    echo 1>&2 "SwiftLint found violations it could not fix."
+    echo "Run swiftlint --fix in your terminal and fix the issues before trying to commit again."
+    echo "       ********************************************      "
+    echo "*********************************************************"
+    #Exit
+    exit 1
+fi
